Facial_recognition_attendance_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls,),

    path('', include('account.urls')),
    # path('', include('attendance.urls')),


]

account/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from account.views import *
from attendance.views import CourseUpdateView, CourseDeleteView, register_in_course, return_course, attendance, \
    attendance_in, edit_attendance, edit_attendance_in, edit_attendance_out

app_name = 'account'
urlpatterns = [
    path('', home, name='home'),
    path('login-page/', login_page, name='login-page'),

    path('student-register/', student_register, name='student-register'),
    path('student-login/', student_login, name='student-login'),
    path('student-profile-update/', student_profile_update, name='student-profile-update'),

    path('lecturer-register/', lecturer_register, name='lecturer-register'),
    path('lecturer-login/', lecturer_login, name='lecturer-login'),
    path('lecturer-profile-update/', lecturer_profile_update, name='lecturer-profile-update'),
    path('edit-attendance/', edit_attendance, name='edit-attendance'),

    path('logout/', user_logout, name='logout'),

    path('detail/<slug:pk>/update/', CourseUpdateView.as_view(), name='course-update'),
    path('detail/<slug:pk>/delete/', CourseDeleteView.as_view(), name='course-delete'),

    path('register/<int:id>/', register_in_course, name='register-course'),
    path('return/<int:id>/', return_course, name='return-course'),

    path('attendance-course/', attendance, name='attendance-course'),
    path('attendance-in/<int:course>/', attendance_in, name='attendance-in'),

    path('train/', train, name='train'),

    path('edit-attendance-in/<int:course>/<str:student>', edit_attendance_in, name='edit-attendance-in'),
    path('edit-attendance-out/<int:course>/<str:student>/', edit_attendance_out, name='edit-attendance-out'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attendance/urls.py
# from django.urls import path, include
# from django.conf.urls.static import static
# from django.conf import settings
#
# from attendance.views import *
#
# app_name = 'attendance'
# urlpatterns = [
#
#
#     # path('detail/<slug:pk>/update', CourseUpdateView.as_view(), name='course-update'),
#     # path('detail/<slug:pk>/delete', CourseDeleteView.as_view(), name='course-delete'),
#
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attendance/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class Course(models.Model):
    name = models.CharField(_("Course Name"), max_length=255)
    lecturer = models.ForeignKey(User,
                                 on_delete=models.CASCADE,
                                 related_name="Lecturer",
                                 verbose_name=_("User"))
    date = models.DateField(null=True)
    time = models.TimeField(null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Course")


class Attendance(models.Model):
    student = models.ForeignKey(User,
                                on_delete=models.CASCADE,
                                related_name="Student",
                                verbose_name=_("User"))
    course = models.ForeignKey(Course,
                               on_delete=models.CASCADE,
                               related_name="CourseName",
                               verbose_name=_("Course"))
    is_present = models.BooleanField(default=False, verbose_name=_("Is Present"))

    def __str__(self):
        return self.student.username

    class Meta:
        verbose_name = _("Attendance")

attendance/forms.py
from django import forms
from django.forms import widgets

from attendance.models import Course, Attendance


class CourseForm(forms.ModelForm):

    class Meta:
        model = Course
        fields = ('name',)


class AttendanceForm(forms.ModelForm):

    class Meta:
        model = Attendance
        fields = ('course',)

    def clean_data(request, self):

        cd = self.cleaned_data
        if Attendance.objects.filter(course=cd['course']).filter(student=request.user.id):
            raise forms.ValidationError("The phone is already exist!")
        return cd['course']

attendance/views.py
import face_recognition
from imutils import face_utils
from imutils.video import VideoStream
from imutils.face_utils import FaceAligner
import time
from sklearn.preprocessing import LabelEncoder
import datetime
import pickle
import dlib
import cv2
import imutils
import numpy as np
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, DeleteView

from account.admin import User
from attendance.forms import CourseForm
from attendance.models import Course, Attendance


class CourseUpdateView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    model = Course
    template_name = 'attendance/course_update.html'
    form_class = CourseForm
    success_url = '/'

    def form_valid(self, form):
        form.instance.lecturer = self.request.user
        return super().form_valid(form)

    def test_func(self):
        course = self.get_object()
        if self.request.user == course.lecturer:
            return True
        else:
            return False


class CourseDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Course
    success_url = '/'

    def test_func(self):
        course = self.get_object()
        if self.request.user == course.lecturer:
            return True
        else:
            return False


@login_required(login_url='/student-login/')
def return_course(request, id):
    Attendance.objects.get(id=id).delete()

    msg = 'returned the course'
    messages.add_message(request, messages.INFO, msg)
    return HttpResponseRedirect("/")


@login_required(login_url='/student-login/')
def register_in_course(request, id):
    course = Course.objects.get(id=id)
    t = Attendance(student=request.user, course=course)
    t.save()
    msg = 'Done'
    messages.add_message(request, messages.SUCCESS, msg)
    return HttpResponseRedirect("/")


@login_required(login_url='/student-login/')
def attendance(request):
    course = Attendance.objects.filter(student=request.user.id)
    return render(request, 'attendance/attendance.html', {
        'course': course

    }, )


def predict(face_aligned, svc, threshold=0.7):
    face_encodings = np.zeros((1, 128))
    try:
        x_face_locations = face_recognition.face_locations(face_aligned)
        faces_encodings = face_recognition.face_encodings(face_aligned, known_face_locations=x_face_locations)
        if (len(faces_encodings) == 0):
            return ([-1], [0])

    except:

        return ([-1], [0])

    prob = svc.predict_proba(faces_encodings)
    result = np.where(prob[0] == np.amax(prob[0]))
    if prob[0][result[0]] <= threshold:
        return [-1], prob[0][result[0]]

    return result[0], prob[0][result[0]]


def update_attendance(request, present, id):
    print("person", present)
    for person in present:
        print(" chack", present[person]==True)
        if present[person] == True:
            student = User.objects.get(username=person)
            print("person", person)

            try:
                qc = Course.objects.get(id=id)
            except:
                qc = None
            try:
                qs = Attendance.objects.get(student=student, course=qc)
            except:
                qs = None

            if qs is None:

                msg = (
                        'it,s not same')
                messages.add_message(request, messages.WARNING, msg)

            else:
                if present[person] == True:
                    now = datetime.datetime.now()
                    qs.is_present = True
                    qs.save(update_fields=['is_present'])
                    qc.date = datetime.date.today()
                    qc.time = now.time()
                    qc.save(update_fields=['date', 'time'])
                    msg = (
                        'done')
                    messages.add_message(request, messages.SUCCESS, msg)

        # else:
        #
        #     msg = (
        #         'it,s not same')
        #     messages.add_message(request, messages.WARNING, msg)


def attendance_in(request, course):
    detector = dlib.get_frontal_face_detector()

    predictor = dlib.shape_predictor(
        'account/face_recognition_data/shape_predictor_68_face_landmarks.dat')  # Add path to the shape predictor ######CHANGE TO RELATIVE PATH LATER
    svc_save_path = "account/face_recognition_data/svc.sav"

    with open(svc_save_path, 'rb') as f:
        svc = pickle.load(f)
    fa = FaceAligner(predictor, desiredFaceWidth=96)
    encoder = LabelEncoder()
    encoder.classes_ = np.load('account/face_recognition_data/classes.npy')

    faces_encodings = np.zeros((1, 128))
    no_of_faces = len(svc.predict_proba(faces_encodings)[0])
    count = dict()
    present = dict()
    log_time = dict()
    start = dict()
    for i in range(no_of_faces):
        count[encoder.inverse_transform([i])[0]] = 0
        present[encoder.inverse_transform([i])[0]] = False

    vs = VideoStream(src=0).start()

    sampleNum = 0

    while (True):

        frame = vs.read()
        print(frame)
        frame = imutils.resize(frame, width=800)

        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        faces = detector(gray_frame, 0)

        for face in faces:
            print("INFO : inside for loop")
            (x, y, w, h) = face_utils.rect_to_bb(face)

            face_aligned = fa.align(frame, gray_frame, face)
            cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 1)

            (pred, prob) = predict(face_aligned, svc)

            if (pred != [-1]):

                person_name = encoder.inverse_transform(np.ravel([pred]))[0]
                pred = person_name
                if count[pred] == 0:
                    start[pred] = time.time()
                    count[pred] = count.get(pred, 0) + 1

                if count[pred] == 4 and (time.time() - start[pred]) > 1.2:
                    count[pred] = 0
                else:
                    # if count[pred] == 4 and (time.time()-start) <= 1.5:
                    present[pred] = True
                    log_time[pred] = datetime.datetime.now()
                    count[pred] = count.get(pred, 0) + 1
                    print(pred, present[pred], count[pred])
                cv2.putText(frame, str(person_name) + str(prob), (x + 6, y + h - 6), cv2.FONT_HERSHEY_SIMPLEX, 0.5,
                            (0, 255, 0), 1)

            else:
                person_name = "unknown"
                cv2.putText(frame, str(person_name), (x + 6, y + h - 6), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

        # cv2.putText()
        # Before continuing to the next loop, I want to give it a little pause
        # waitKey of 100 millisecond
        # cv2.waitKey(50)

        # Showing the image in another window
        # Creates a window with window name "Face" and with the image img
        cv2.imshow("Mark Attendance - In - Press q to exit", frame)
        # Before closing it we need to give a wait command, otherwise the open cv wont work
        # @params with the millisecond of delay 1
        # cv2.waitKey(1)
        # To get out of the loop
        key = cv2.waitKey(50) & 0xFF
        if (key == ord("q")):
            break

    # Stoping the videostream
    vs.stop()

    # destroying all the windows
    cv2.destroyAllWindows()
    print(course)
    update_attendance(request, present, course)
    print(present)
    return redirect('/attendance-course/')


def edit_attendance(request):
    course = Attendance.objects.filter(course__lecturer=request.user.id)
    return render(request, 'attendance/edit_attendance.html', {
        'course': course

    }, )


def edit_attendance_in(request, course, student):
    detector = dlib.get_frontal_face_detector()

    predictor = dlib.shape_predictor(
        'account/face_recognition_data/shape_predictor_68_face_landmarks.dat')  # Add path to the shape predictor ######CHANGE TO RELATIVE PATH LATER
    svc_save_path = "account/face_recognition_data/svc.sav"

    with open(svc_save_path, 'rb') as f:
        svc = pickle.load(f)
    fa = FaceAligner(predictor, desiredFaceWidth=96)
    encoder = LabelEncoder()
    encoder.classes_ = np.load('account/face_recognition_data/classes.npy')

    faces_encodings = np.zeros((1, 128))
    no_of_faces = len(svc.predict_proba(faces_encodings)[0])
    count = dict()
    present = dict()
    log_time = dict()
    start = dict()
    for i in range(no_of_faces):
        count[encoder.inverse_transform([i])[0]] = 0
        present[encoder.inverse_transform([i])[0]] = False

    vs = VideoStream(src=0).start()

    sampleNum = 0

    while (True):

        frame = vs.read()

        frame = imutils.resize(frame, width=800)

        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        faces = detector(gray_frame, 0)

        for face in faces:
            print("INFO : inside for loop")
            (x, y, w, h) = face_utils.rect_to_bb(face)

            face_aligned = fa.align(frame, gray_frame, face)
            cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 1)

            (pred, prob) = predict(face_aligned, svc)

            if (pred != [-1]):

                person_name = encoder.inverse_transform(np.ravel([pred]))[0]
                pred = person_name
                if count[pred] == 0:
                    start[pred] = time.time()
                    count[pred] = count.get(pred, 0) + 1

                if count[pred] == 4 and (time.time() - start[pred]) > 1.2:
                    count[pred] = 0
                else:
                    # if count[pred] == 4 and (time.time()-start) <= 1.5:
                    present[pred] = True
                    log_time[pred] = datetime.datetime.now()

attendance/templates/attendance/attendance.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
<div class="container-xxl flex-grow-1 container-p-y">
                          <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Tables /</span> Course</h4>
                            {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">
                                    {{message}}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                             </div>
                            {% endfor %}
                          {% endif %}

                          <!-- Basic Bootstrap Table -->
                          <div class="card">
                            <h5 class="card-header">Your Course</h5>
                            <div class="table-responsive text-nowrap">
                              <table class="table">
                                <thead>
                                  <tr>
                                    <th>Course</th>
                                    <th>Student</th>
                                    <th>Name</th>
                                    <th>State</th>
                                    <th>Attendance Date</th>
                                    <th>Attendance Time</th>
                                    <th>Presence</th>
                                  </tr>
                                </thead>
                                <tbody class="table-border-bottom-0">
                                {% for q_course in course %}
                                  <tr>

                                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{{ q_course.course.name }}</strong></td>
                                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{{ user.username }}</strong></td>
                                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{{user.first_name}}{{user.last_name}}</strong></td>
                                        <td style="width:15%">
                                            {% if q_course.is_present %}
                                            <img style="width: 35%;" src="{% static 'attendance/assets/img/c.png' %}">
                                            {% else %}
                                            <img style="width: 35%;" src="{% static 'attendance/assets/img/w.png' %}">
                                            {% endif %}
                                        </td>
                                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{% if q_course.course.date %}{{ q_course.course.date }}{% else %} - {% endif %}</strong></td>
                                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{% if q_course.course.time %}{{ q_course.course.time }}{% else %} - {% endif %}</strong></td>
                                        <td>
                                          <div class="dropdown">
                                            <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                              <i class="bx bx-dots-vertical-rounded"></i>
                                            </button>
                                            <div class="dropdown-menu">
                                              <a class="dropdown-item" href="{% url "account:attendance-in" q_course.course.id %}"
                                                ><i class="bx bx-edit-alt me-1"></i>Present</a
                                              >

                                            </div>
                                          </div>
                                        </td>

                                  </tr>
                                {% endfor %}
                                </tbody>
                              </table>
                            </div>
                          </div>


            </div>
{% endblock body %}

attendance/templates/attendance/course.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="col-md-12">
                  <div class="card mb-4">
                    <h5 class="card-header">Add Course</h5>
                    <div class="card-body">
                      <div>
                          {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">
                                    {{message}}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                             </div>
                            {% endfor %}
                          {% endif %}
                         <form method="POST">
                        {% csrf_token %}
                        {{form|crispy}}
                        <input class="btn btn-secondary mt-4" type="submit" value="save">
                    </form>
                      </div>
                    </div>
                  </div>
                </div>
            <hr class="my-5" />
{% endblock body %}

attendance/templates/attendance/course_confirm_delete.html
{% extends 'base.html' %}
{% block body %}
{% load crispy_forms_tags %}

<div class="border p-4 mb-5">
    {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">
                                    {{message}}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                             </div>
                            {% endfor %}
                          {% endif %}
    <legend class="border-bottom pb-1 mb-3">Delete Course</legend>
    <form method="POST">
        <legend class="pb-1 mb-3 mt-4"> "Are you sure to delete ({{object.name}})?" </legend>
        {% csrf_token %}
        <input class="btn btn-danger mt-3" type="submit" value="Delete">
        <a class="btn btn-secondary mt-3 back-btn" href="/">Back</a>
    </form>
</div>
{% endblock body %}

attendance/templates/attendance/course_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block body %}
<div class="col-md-12">
      <div class="card mb-4">
                    <h5 class="card-header">Add Course</h5>
                    <div class="card-body">
                      <div>
                          {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">
                                    {{message}}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                             </div>
                            {% endfor %}
                          {% endif %}
                         <form method="POST">
                        {% csrf_token %}
                        {{form|crispy}}
                        <input class="btn btn-secondary mt-4" type="submit" value="save">
                    </form>
                      </div>
                    </div>
                  </div>
</div>
{% endblock body %}

attendance/templates/attendance/edit_attendance.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
<div class="container-xxl flex-grow-1 container-p-y">
                          <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Tables /</span> Course</h4>
                          {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">
                                    {{message}}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                             </div>
                            {% endfor %}
                          {% endif %}
                          <!-- Basic Bootstrap Table -->
                          <div class="card">
                            <h5 class="card-header">Your Course</h5>
                            <div class="table-responsive text-nowrap">
                              <table class="table">
                                <thead>
                                  <tr>
                                    <th>Course</th>
                                    <th>Student</th>
                                    <th>Name</th>
                                    <th>State</th>
                                    <th>Attendance Date</th>
                                    <th>Attendance Time</th>
                                    <th>Presence</th>
                                  </tr>
                                </thead>
                                <tbody class="table-border-bottom-0">
                                {% for q_course in course %}
                                  <tr>

                                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{{ q_course.course.name }}</strong></td>
                                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{{ q_course.student }}</strong></td>
                                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{{ q_course.student.first_name }}{{ q_course.student.last_name }}</strong></td>
                                        <td style="width:15%">
                                            {% if q_course.is_present %}
                                            <img style="width: 35%;" src="{% static 'attendance/assets/img/c.png' %}">
                                            {% else %}
                                            <img style="width: 35%;" src="{% static 'attendance/assets/img/w.png' %}">
                                            {% endif %}
                                        </td>
                                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{% if q_course.course.date %}{{ q_course.course.date }}{% else %} - {% endif %}</strong></td>
                                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{% if q_course.course.time %}{{ q_course.course.time }}{% else %} - {% endif %}</strong></td>


                                        <td>
                                          <div class="dropdown">
                                            <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                              <i class="bx bx-dots-vertical-rounded"></i>
                                            </button>
                                            <div class="dropdown-menu">
                                              <a class="dropdown-item" href="{% url "account:edit-attendance-in" q_course.course.id q_course.student.id  %}"
                                                ><i class="bx bx-edit-alt me-1"></i>Present</a
                                              >
                                                <a class="dropdown-item" href="{% url "account:edit-attendance-out" q_course.course.id q_course.student.id  %}"
                                                ><i class="bx bx-edit-alt me-1"></i>Absent</a>

                                            </div>
                                          </div>
                                        </td>

                                  </tr>
                                {% endfor %}
                                </tbody>
                              </table>
                            </div>
                          </div>


            </div>
{% endblock body %}

attendance/templates/attendance/table.html
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}