Facial_recognition_attendance_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls,),

    path('', include('account.urls')),
    # path('', include('attendance.urls')),


]

account/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from account.views import *
from attendance.views import CourseUpdateView, CourseDeleteView, register_in_course, return_course, attendance, \
    attendance_in, edit_attendance, edit_attendance_in, edit_attendance_out

app_name = 'account'
urlpatterns = [
    path('', home, name='home'),
    path('login-page/', login_page, name='login-page'),

    path('student-register/', student_register, name='student-register'),
    path('student-login/', student_login, name='student-login'),
    path('student-profile-update/', student_profile_update, name='student-profile-update'),

    path('lecturer-register/', lecturer_register, name='lecturer-register'),
    path('lecturer-login/', lecturer_login, name='lecturer-login'),
    path('lecturer-profile-update/', lecturer_profile_update, name='lecturer-profile-update'),
    path('edit-attendance/', edit_attendance, name='edit-attendance'),

    path('logout/', user_logout, name='logout'),

    path('detail/<slug:pk>/update/', CourseUpdateView.as_view(), name='course-update'),
    path('detail/<slug:pk>/delete/', CourseDeleteView.as_view(), name='course-delete'),

    path('register/<int:id>/', register_in_course, name='register-course'),
    path('return/<int:id>/', return_course, name='return-course'),

    path('attendance-course/', attendance, name='attendance-course'),
    path('attendance-in/<int:course>/', attendance_in, name='attendance-in'),

    path('train/', train, name='train'),

    path('edit-attendance-in/<int:course>/<str:student>', edit_attendance_in, name='edit-attendance-in'),
    path('edit-attendance-out/<int:course>/<str:student>/', edit_attendance_out, name='edit-attendance-out'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attendance/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class Course(models.Model):
    name = models.CharField(_("Course Name"), max_length=255)
    lecturer = models.ForeignKey(User,
                                 on_delete=models.CASCADE,
                                 related_name="Lecturer",
                                 verbose_name=_("User"))
    date = models.DateField(null=True)
    time = models.TimeField(null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Course")


class Attendance(models.Model):
    student = models.ForeignKey(User,
                                on_delete=models.CASCADE,
                                related_name="Student",
                                verbose_name=_("User"))
    course = models.ForeignKey(Course,
                               on_delete=models.CASCADE,
                               related_name="CourseName",
                               verbose_name=_("Course"))
    is_present = models.BooleanField(default=False, verbose_name=_("Is Present"))

    def __str__(self):
        return self.student.username

    class Meta:
        verbose_name = _("Attendance")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html
  lang="en"
  class="light-style layout-menu-fixed"
  dir="ltr"
  data-theme="theme-default"
  data-assets-path="../assets/"
  data-template="vertical-menu-template-free"
>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    <title>AAMUSTED FRAS</title>

    <meta name="description" content="" />

    <!-- Favicon -->
{#    <link rel="icon" type="image/x-icon" href="../assets/img/favicon/favicon.ico" />#}

 {% include "css.html"%}
  </head>

  <body>
        <div class="layout-container">
        <!-- Menu -->

        <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
          <div class="app-brand demo">
            <a href="/" class="app-brand-link">
              <span class="app-brand-logo demo">
                <svg
                  width="25"
                  viewBox="0 0 25 42"
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:xlink="http://www.w3.org/1999/xlink"
                >
                  <defs>
                    <path
                      d="M13.7918663,0.358365126 L3.39788168,7.44174259 C0.566865006,9.69408886 -0.379795268,12.4788597 0.557900856,15.7960551 C0.68998853,16.2305145 1.09562888,17.7872135 3.12357076,19.2293357 C3.8146334,19.7207684 5.32369333,20.3834223 7.65075054,21.2172976 L7.59773219,21.2525164 L2.63468769,24.5493413 C0.445452254,26.3002124 0.0884951797,28.5083815 1.56381646,31.1738486 C2.83770406,32.8170431 5.20850219,33.2640127 7.09180128,32.5391577 C8.347334,32.0559211 11.4559176,30.0011079 16.4175519,26.3747182 C18.0338572,24.4997857 18.6973423,22.4544883 18.4080071,20.2388261 C17.963753,17.5346866 16.1776345,15.5799961 13.0496516,14.3747546 L10.9194936,13.4715819 L18.6192054,7.984237 L13.7918663,0.358365126 Z"
                      id="path-1"
                    ></path>
                    <path
                      d="M5.47320593,6.00457225 C4.05321814,8.216144 4.36334763,10.0722806 6.40359441,11.5729822 C8.61520715,12.571656 10.0999176,13.2171421 10.8577257,13.5094407 L15.5088241,14.433041 L18.6192054,7.984237 C15.5364148,3.11535317 13.9273018,0.573395879 13.7918663,0.358365126 C13.5790555,0.511491653 10.8061687,2.3935607 5.47320593,6.00457225 Z"
                      id="path-3"
                    ></path>
                    <path
                      d="M7.50063644,21.2294429 L12.3234468,23.3159332 C14.1688022,24.7579751 14.397098,26.4880487 13.008334,28.506154 C11.6195701,30.5242593 10.3099883,31.790241 9.07958868,32.3040991 C5.78142938,33.4346997 4.13234973,34 4.13234973,34 C4.13234973,34 2.75489982,33.0538207 2.37032616e-14,31.1614621 C-0.55822714,27.8186216 -0.55822714,26.0572515 -4.05231404e-15,25.8773518 C0.83734071,25.6075023 2.77988457,22.8248993 3.3049379,22.52991 C3.65497346,22.3332504 5.05353963,21.8997614 7.50063644,21.2294429 Z"
                      id="path-4"
                    ></path>
                    <path
                      d="M20.6,7.13333333 L25.6,13.8 C26.2627417,14.6836556 26.0836556,15.9372583 25.2,16.6 C24.8538077,16.8596443 24.4327404,17 24,17 L14,17 C12.8954305,17 12,16.1045695 12,15 C12,14.5672596 12.1403557,14.1461923 12.4,13.8 L17.4,7.13333333 C18.0627417,6.24967773 19.3163444,6.07059163 20.2,6.73333333 C20.3516113,6.84704183 20.4862915,6.981722 20.6,7.13333333 Z"
                      id="path-5"
                    ></path>
                  </defs>
                  <g id="g-app-brand" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                    <g id="Brand-Logo" transform="translate(-27.000000, -15.000000)">
                      <g id="Icon" transform="translate(27.000000, 15.000000)">
                        <g id="Mask" transform="translate(0.000000, 8.000000)">
                          <mask id="mask-2" fill="white">
                            <use xlink:href="#path-1"></use>
                          </mask>
                          <use fill="#696cff" xlink:href="#path-1"></use>
                          <g id="Path-3" mask="url(#mask-2)">
                            <use fill="#696cff" xlink:href="#path-3"></use>
                            <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-3"></use>
                          </g>
                          <g id="Path-4" mask="url(#mask-2)">
                            <use fill="#696cff" xlink:href="#path-4"></use>
                            <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-4"></use>
                          </g>
                        </g>
                        <g
                          id="Triangle"
                          transform="translate(19.000000, 11.000000) rotate(-300.000000) translate(-19.000000, -11.000000) "
                        >
                          <use fill="#696cff" xlink:href="#path-5"></use>
                          <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-5"></use>
                        </g>
                      </g>
                    </g>
                  </g>
                </svg>
              </span>
              <span class=" demo menu-text fw-bolder ms-2">AAMUSTED FRAS</span>
            </a>

            <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
              <i class="bx bx-chevron-left bx-sm align-middle"></i>
            </a>
          </div>

          <div class="menu-inner-shadow"></div>

          <ul class="menu-inner py-1">
            <!-- Dashboard -->
            <li class="menu-item active">
              <a href="/" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-circle"></i>
                <div data-i18n="Analytics">Home</div>
              </a>

            {% if user.is_student  %}
            <li class="menu-header small text-uppercase">
              <span class="menu-header-text">Course</span>
            </li>
                </li><li class="menu-item ">
              <a href="{% url "account:attendance-course" %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-detail"></i>
                <div data-i18n="Analytics">Attendance</div>
              </a>
            </li>
            {% else %}
             </li><li class="menu-item ">
              <a href="{% url "account:edit-attendance"  %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-detail"></i>
                <div data-i18n="Analytics">Attendance</div>
              </a>
            </li>
            {% endif %}

          </ul>
        </aside>
        <!-- / Menu -->


          <!-- / Navbar -->
<div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">
        <!-- Menu -->

        <!-- / Menu -->

        <!-- Layout container -->
        <div class="layout-page">
          <!-- Navbar -->

          <nav
            class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
            id="layout-navbar"
          >
            <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
              <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                <i class="bx bx-menu bx-sm"></i>
              </a>
            </div>

            <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
              <!-- Search -->
              <div class="navbar-nav align-items-center">
                <div class="nav-item d-flex align-items-center">

                </div>
              </div>
              <!-- /Search -->

              <ul class="navbar-nav flex-row align-items-center ms-auto">
                <!-- Place this tag where you want the button to render. -->
                <!-- User -->
                <li class="nav-item navbar-dropdown dropdown-user dropdown">
                  <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                    <div class="avatar avatar-online">
                        {% if user.is_student  %}
                            <img src="{% static "attendance/assets/img/student.png" %}" alt class="w-px-40 h-auto rounded-circle" />
                        {% else %}
                            <img src="{% static "attendance/assets/img/lecturer.png" %}" alt class="w-px-40 h-auto rounded-circle" />
                        {% endif %}
                    </div>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                      <a class="dropdown-item" href="/">
                        <div class="d-flex">
                          <div class="flex-shrink-0 me-3">
                            <div class="avatar avatar-online">

                              {% if user.is_student  %}
                                    <img src="{% static "attendance/assets/img/student.png" %}" alt class="w-px-40 h-auto rounded-circle" />
                              {% else %}
                                    <img src="{% static "attendance/assets/img/lecturer.png" %}" alt class="w-px-40 h-auto rounded-circle" />
                              {% endif %}

                            </div>
                          </div>
                          <div class="flex-grow-1">
                            <span class="fw-semibold d-block">{{user.first_name}}{{user.last_name}}</span>
                          </div>
                        </div>
                      </a>
                    </li>
                    <li>
                      <div class="dropdown-divider"></div>
                    </li>
                    <li>
                        {% if user.is_student  %}
                          <a class="dropdown-item" href="{% url "account:student-profile-update" %}">
                            <i class="bx bx-user me-2"></i>
                            <span class="align-middle">My Profile</span>
                          </a>
                        {% elif user.is_lecturer %}
                          <a class="dropdown-item" href="{% url "account:lecturer-profile-update" %}">
                            <i class="bx bx-user me-2"></i>
                            <span class="align-middle">My Profile</span>
                          </a>
                        {% else %}

                        {% endif %}

                    </li>
                    <li>
                      <div class="dropdown-divider"></div>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url "account:logout" %}">
                        <i class="bx bx-power-off me-2"></i>
                        <span class="align-middle">Log Out</span>
                      </a>
                    </li>
                  </ul>
                </li>
                <!--/ User -->
              </ul>
            </div>
          </nav>

          <!-- / Navbar -->

          <!-- Content wrapper -->
                         <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
            {% block body %}

            {% endblock body %}
            </div>

            <!-- / Content -->

            <!-- Footer -->
            <footer class="content-footer footer bg-footer-theme">
              <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                <div class="mb-2 mb-md-0">
                  ©
                  <script>
                    document.write(new Date().getFullYear());
                  </script>
                  , made with ❤️ by
                  <a href="https://www.linkedin.com/in/mahmoud-alforawi-72b02a101/" target="_blank" class="footer-link fw-bolder">Mahmoud Alforawi</a>
                </div>
              </div>
            </footer>
            <!-- / Footer -->

            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->

          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>

      <!-- Overlay -->
      <div class="layout-overlay layout-menu-toggle"></div>
    </div>

          <!-- Content wrapper -->

          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>
    <!-- Layout wrapper -->

    <!-- / Layout wrapper -->

    <!-- Core JS -->
    {% include "js.html" %}
  </body>
</html>

templates/css.html
   {% load static %}
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="{% static 'attendance/assets/vendor/fonts/boxicons.css' %}" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="{% static 'attendance/assets/vendor/css/core.css' %}" class="template-customizer-core-css" />
    <link rel="stylesheet" href="{% static 'attendance/assets/vendor/css/theme-default.css ' %}" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="{% static 'attendance/assets/css/demo.css' %}" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="{% static 'attendance/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}" />

    <link rel="stylesheet" href="{% static 'attendance/assets/vendor/libs/apex-charts/apex-charts.css' %}" />

    <!-- Page CSS -->
    <link rel="stylesheet" href="{% static 'attendance/assets/vendor/css/pages/page-auth.css' %}" />

    <!-- Helpers -->
    <script src="{% static 'attendance/assets/vendor/js/helpers.js ' %}"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="{% static 'attendance/assets/js/config.js' %}"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/solid.min.css"></script>

templates/index.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
    {% if messages %}
      {% for message in messages %}
          <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">
              {{message}}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
      {% endfor %}
    {% endif %}
         {% if user.is_lecturer  %}
           <div class="col-md-12">
                  <div class="card mb-4">
                    <h5 class="card-header">Add Course</h5>
                    <div class="card-body">
                      <div>
                         <form method="POST">
                        {% csrf_token %}
{#                        {{form_course|crispy}}#}
                             <div id="div_id_name" class="form-group">
                             <label for="id_name" class=" requiredField">Course Name<span class="asteriskField">*</span> </label>
                             <div> <input type="text" name="name" maxlength="255" class="textinput textInput form-control" required="" id="id_name" data-dashlane-rid="79f13db9190542aa" data-form-type="" data-kwimpalaid="1661892687787-0"> </div> </div>
                        <input class="btn btn-secondary mt-4" name="course_form" id="course_form" type="submit" value="save">
                    </form>
                      </div>
                    </div>
                  </div>
                </div>
            <hr class="my-5" />
            <div class="container-xxl flex-grow-1 container-p-y">
              <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Tables /</span> Course</h4>

              <!-- Basic Bootstrap Table -->
              <div class="card">
                <h5 class="card-header">Table Basic</h5>
                <div class="table-responsive text-nowrap">
                  <table class="table">
                    <thead>
                      <tr>
                        <th>Course</th>
                        <th>Date</th>
                        <th>Time</th>
                        <th>Actions</th>
                      </tr>
                    </thead>
                    <tbody class="table-border-bottom-0">
                    {% for q_course in lecturer_course %}
                      <tr>

                           <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{{ q_course.name }}</strong></td>
                          <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{% if q_course.date %}{{ q_course.date }}{% else %} - {% endif %}</strong></td>
                          <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{% if q_course.time %}{{ q_course.time }}{% else %} - {% endif %}</strong></td>
                          <td>
                              <div class="dropdown">
                                <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                  <i class="bx bx-dots-vertical-rounded"></i>
                                </button>
                                <div class="dropdown-menu">
                                  <a class="dropdown-item" href="{% url "account:course-update" q_course.id %}"
                                    ><i class="bx bx-edit-alt me-1"></i> Edit</a
                                  >
                                  <a class="dropdown-item" href="{% url "account:course-delete" q_course.id%}"
                                    ><i class="bx bx-trash me-1"></i> Delete</a
                                  >
                                </div>
                              </div>
                            </td>

                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
              <!--/ Basic Bootstrap Table -->

            </div>
         {% elif user.is_superuser %}
             <h1>hello {{user.first_name}}{{user.last_name}}</h1>
             {% if student_num > 1 %}
             <a href="{% url 'account:train' %}" class="btn btn-success ">
                   <span class="tf-icons bx bx-pie-chart-alt"></span>&nbsp; Training Model
             </a>
                 {% else %}
                  <a href="{% url 'account:train' %}" class="btn btn-success disabled">
                   <span class="tf-icons bx bx-pie-chart-alt"></span>&nbsp; Training Model
             </a>
             <p style="color: #d93519">it should be have more than one student to train </p>
                 {% endif %}
             <a href="/admin/" class="btn btn-primary">
                   <span class="tf-icons bx bxs-dashboard"></span>&nbsp; Admin Dashboard
             </a>
         {% else %}
            <div class="col-md-12">
                              <div class="card mb-4">
                                <h5 class="card-header">Register</h5>
                                <div class="card-body">
                                  <div>
                                     <form method="POST">
                                    {% csrf_token %}
                                    {{form_attendance|crispy}}
                                    <input class="btn btn-secondary mt-4" id="attendance" name="attendance" type="submit" value="save">
                                </form>
                                  </div>
                                </div>
                              </div>
                            </div>
                        <hr class="my-5" />
                        <div class="container-xxl flex-grow-1 container-p-y">
                          <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Tables /</span> Course</h4>

                          <!-- Basic Bootstrap Table -->
                          <div class="card">
                            <h5 class="card-header">Your Course</h5>
                            <div class="table-responsive text-nowrap">
                              <table class="table">
                                <thead>
                                  <tr>
                                    <th>Course</th>
                                    <th>Teacher</th>
                                    <th>Date</th>
                                    <th>Time</th>
                                    <th>Return</th>
                                  </tr>
                                </thead>
                                <tbody class="table-border-bottom-0">
                                {% for q_course in course %}
                                  <tr>

                                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{{ q_course.course.name }}</strong></td>
                                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{{ q_course.course.lecturer }}</strong></td>
                                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{% if q_course.course.date %}{{ q_course.course.date }}{% else %} - {% endif %}</strong></td>
                                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{% if q_course.course.time %}{{ q_course.course.time }}{% else %} - {% endif %}</strong></td>

                                        <td>
                                          <div class="dropdown">
                                            <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                              <i class="bx bx-dots-vertical-rounded"></i>
                                            </button>
                                            <div class="dropdown-menu">
                                              <a class="dropdown-item" href="{% url "account:return-course" q_course.id %}"
                                                ><i class="bx bx-edit-alt me-1"></i>Return</a
                                              >

                                            </div>
                                          </div>
                                        </td>

                                  </tr>
                                {% endfor %}
                                </tbody>
                              </table>
                            </div>
                          </div>


            </div>
         {% endif %}

{% endblock body %}

templates/login_page.html
{% load static %}
<!DOCTYPE html>
<html
  lang="en"
  class="light-style"
  dir="ltr"
  data-theme="theme-default"
  data-assets-path="../assets/"
  data-template="vertical-menu-template-free"
>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    <title>AAMUSTED FRAS</title>

    <meta name="description" content="" />

    <!-- Favicon -->

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />
      {% include "css.html" %}

    <!-- Icons. Uncomment required icon fonts -->
  </head>

  <body>
    <!-- Content -->

    <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">
        <!-- Menu -->

        <!-- Layout container -->
        <div class="layout-page">
          <!-- Navbar -->
          <!-- / Navbar -->

          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->
<a href="/admin/"  class="btn btn-primary">
               <span class="tf-icons bx bxs-user"></span>&nbsp; LOGIN AS ADMIN
            </a>
            <div class="container-xxl flex-grow-1 container-p-y">

              <!-- Examples -->
              <div class="row mb-5">
                <div class="col-md-4 col-lg-6 mb-2">
                  <div class="card h-100">
                    <img class="card-img-top" src="{% static 'attendance/assets/img/elements/2.jpg' %}" alt="Card image cap" />
                    <div class="card-body">
                      <h5 class="card-title">Login as Student</h5>
                      <a href="{% url 'account:student-login' %}" class="btn btn-outline-primary">Student Login</a>
                    </div>
                  </div>
                </div>
                <div class="col-md-4 col-lg-6 mb-2">
                  <div class="card h-100">
                    <img class="card-img-top" src="{% static 'attendance/assets/img/elements/2.jpg' %}" alt="Card image cap" />
                    <div class="card-body">
                      <h5 class="card-title">Login as lecturer</h5>
                      <a href="{% url "account:lecturer-login" %}" class="btn btn-outline-primary">lecturer Login</a>
                    </div>
                  </div>
                </div>

              </div>
              <!-- Examples -->

              <!-- Card Groups -->

              <!--/ Card layout -->
            </div>
            <!-- / Content -->

            <!-- Footer -->
            <footer class="content-footer footer bg-footer-theme">
              <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                <div class="mb-2 mb-md-0">
                  ©
                  <script>
                    document.write(new Date().getFullYear());
                  </script>
                  , made with ❤️ by
                  <a href="https://www.linkedin.com/in/mahmoud-alforawi-72b02a101/" target="_blank" class="footer-link fw-bolder">Mahmoud Alforawi</a>
                </div>
              </div>
            </footer>
            <!-- / Footer -->

            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>

      <!-- Overlay -->
      <div class="layout-overlay layout-menu-toggle"></div>
    </div>
    <!-- / Content -->

    {% include "js.html" %}
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="../assets/vendor/libs/jquery/jquery.js"></script>
    <script src="../assets/vendor/libs/popper/popper.js"></script>
    <script src="../assets/vendor/js/bootstrap.js"></script>
    <script src="../assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

    <script src="../assets/vendor/js/menu.js"></script>
    <!-- endbuild -->

    <!-- Vendors JS -->

    <!-- Main JS -->
    <script src="../assets/js/main.js"></script>

    <!-- Page JS -->

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
  </body>
</html>